title: Rijks ICT Gilde
email: RIG@rijksoverheid.nl
description: >-
  Rijks ICT Gilde
baseurl: "" # the subpath of your site, e.g. /blog
source: .
timezone: Europe/Amsterdam
url: "https://rijksictgilde.github.com"
github_username: rijksictgilde

postcss:
  cache: false

plugins:
  - jekyll-feed

liquid:
  error_mode: warn

verbose: true

exclude:
  - package.json
  - Makefile
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules
  - .gitignore
  - .devcontainer
  - .vscode
  - .github
