title: Rijks ICT Gilde
email: RIG@rijksoverheid.nl
description: >- # this means to ignore newlines until "baseurl:"
    Rijks ICT Gilde
baseurl: "" # the subpath of your site, e.g. /blog
source: .
timezone: Europe/Amsterdam
url: "rijksictgilde.github.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: rijksictgilde

remote_theme: pages-themes/hacker@v0.2.0
plugins:
    - jekyll-feed
    - jekyll-remote-theme

liquid:
    error_mode: warn

verbose: true

sass:
    style: compressed
    sourcemap: development

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge
