title: Rijks ICT Gilde
description: >-
    Rijks ICT Gilde
source: .
timezone: Europe/Amsterdam
url: "https://rijksictgilde.github.io"
baseurl: ""

postcss:
    cache: false

markdown_ext: "md"

kramdown:
  syntax_highlighter: coderay

exclude:
    - package.json
    - Makefile
    - postcss.config.js
    - tailwind.config.js
    - yarn.lock
    - .gitignore
    - .devcontainer
    - .vscode
    - .github
    - node_modules
    - Gemfile
    - Gemfile.lock

sass:
    style: compressed
    sourcemap: development

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

